[2022-07-22 14:10:06,955] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data.load_dataset scheduled__2022-07-06T02:00:00+00:00 [queued]>
[2022-07-22 14:10:06,958] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: load_data.load_dataset scheduled__2022-07-06T02:00:00+00:00 [queued]>
[2022-07-22 14:10:06,958] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:10:06,958] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-07-22 14:10:06,958] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 14:10:06,967] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): load_dataset> on 2022-07-06 02:00:00+00:00
[2022-07-22 14:10:06,969] {standard_task_runner.py:52} INFO - Started process 17937 to run task
[2022-07-22 14:10:06,971] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'load_data', 'load_dataset', 'scheduled__2022-07-06T02:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_data_loader.py', '--cfg-path', '/tmp/tmpnfvqomoe', '--error-file', '/tmp/tmpt0gj3ozg']
[2022-07-22 14:10:06,971] {standard_task_runner.py:80} INFO - Job 21: Subtask load_dataset
[2022-07-22 14:10:06,980] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 14:10:06,981] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-07-22 14:10:06,994] {task_command.py:371} INFO - Running <TaskInstance: load_data.load_dataset scheduled__2022-07-06T02:00:00+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-07-22 14:10:07,020] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=load_data
AIRFLOW_CTX_TASK_ID=load_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-06T02:00:00+00:00
[2022-07-22 14:10:07,035] {base.py:68} INFO - Using connection ID 'postgres_connection' for task execution.
[2022-07-22 14:10:07,041] {sql.py:255} INFO - Running statement: COPY raw_data FROM '/home/hp/Downloads/t_data.csv' WITH DELIMITER AS ';' NULL AS '\null' CSV HEADER;, parameters: None
[2022-07-22 14:10:07,042] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 234, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/hp/miniconda3/envs/airflow_env/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 260, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bigint: " Motorcycle"
CONTEXT:  COPY raw_data, line 2, column track_id: " Motorcycle"

[2022-07-22 14:10:07,044] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=load_data, task_id=load_dataset, execution_date=20220706T020000, start_date=20220722T111006, end_date=20220722T111007
[2022-07-22 14:10:07,054] {standard_task_runner.py:92} ERROR - Failed to execute job 21 for task load_dataset (invalid input syntax for type bigint: " Motorcycle"
CONTEXT:  COPY raw_data, line 2, column track_id: " Motorcycle"
; 17937)
[2022-07-22 14:10:07,062] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 14:10:07,074] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
